### ISSUE TITLE
Data Format for Training

### ISSUE THREAD

**Issue by Wooody82** [ahnineamine/Job-Matcher#12]
Hi,
Could you please clarify how the training data should be formatted for the Word2Vec model?
Should the data be a single text file with each line representing a document or sentence?
Are there specific requirements for organizing the data or handling different languages?

Would be great if there any demo or simple data to see.

Thanks

**Comment by ahnineamine** [comment]
Hi @Wooody82, It has been sometime, but if I remember correctly the data should a text file where each line wasa CV (Document). The model it self is language agnostic. Everything is converted into vectors. So for example you can train an English one or Spanish one .. ect.
But I am pretty sure there is much better and newer tech to acheive this. I still remember thaqt BERT was out a year before I implemented this. 
Sadly I dont have any demos.

**Comment by Wooody82** [comment]
Hi @ahnineamine , Thanks for reponse 👍 I will check and see if could find a good model or help online.
